select * from dbo.['Master Sheet$'];

select * into Customer from  dbo.['Master Sheet$']; 
select * from Customer;
delete from Customer where [Sl No] is null;

with cte as
(select [Sl No],Cust_Id,Cust_Name,ROW_NUMBER() over(partition by Cust_Id,Cust_Name order by [Sl No]) as Duplicate_Count
from Customer)delete from cte where Duplicate_Count>1;
select * into MasterData from Customer order by [Sl No]; 
select * from MasterData;

drop table Customer;
drop table dbo.['Master Sheet$'];








--Q1 Quarterly generated revenue.

--Order by Revenue
select datename(month,date)as Month_Name,sum(Revenue) as Total_Revenue,sum(Profit) as Total_Profit  from MasterData group by datename(month,date) order by sum(Revenue) desc;
--Order by Month
select datename(month,date)as Month_Name,sum(Revenue) as Total_Revenue,sum(Profit) as Total_Profit  from MasterData group by datename(month,date),month(date) order by MONTH(date);
--Insight: 
--December and January are the top most revenue generating months during the year.
--The quarter query shows us that the revenue 1st and 2nd quarters has performed better than the other 2  quarters.


--Quarter 
select datepart(quarter,date) as Quarter_Part,sum(Revenue) as Total_Revenue,sum(Profit) as Total_Profit  from MasterData group by datepart(quarter,date) order by sum(Revenue) desc;

--Q2 Comparision of quarter wise states's Revenue and Profit.
select top(3) datepart(qq,date) as Quarter_n,State,sum(revenue) as Total_Revenue,sum(Profit) as Total_Profit from MasterData group by State,datepart(qq,date) having datepart(qq,date)=1 order by Total_Revenue desc;
select top(3) datepart(qq,date) as Quarter_n,State,sum(revenue) as Total_Revenue,sum(Profit) as Total_Profit from MasterData group by State,datepart(qq,date) having datepart(qq,date)=2 order by Total_Revenue desc;
select top(3) datepart(qq,date) as Quarter_n,State,sum(revenue) as Total_Revenue,sum(Profit) as Total_Profit from MasterData group by State,datepart(qq,date) having datepart(qq,date)=3 order by Total_Revenue desc;
select top(3) datepart(qq,date) as Quarter_n,State,sum(revenue) as Total_Revenue,sum(Profit) as Total_Profit from MasterData group by State,datepart(qq,date) having datepart(qq,date)=4 order by Total_Revenue desc;
--Karnataka has been the most consistent revenue generating state across all the quarters(except Q1).





--Q3 Calculate the revenue generated in the metro cities.
select State,sum(Revenue) as Total_Revenue_Metro,sum(Profit)as Total_Profit_Metro ,count([Payment Mode]) as Count_Payment from MasterData group by State,[Payment Mode] having State in ('Maharashtra','West Bengal','Tamil-Nadu','Delhi') and [Payment Mode]='Online';

--This query shows us that Delhi has not contributed anything to online payment.

--Q4 Comparision of count of online payments between metro and non-metro states.
select State,sum(Revenue) as Total_Revenue_Metro,sum(Profit)as Total_Profit_Metro ,count([Payment Mode]) as Count_Payment from MasterData group by State,[Payment Mode] having State not in ('Maharashtra','West Bengal','Tamil-Nadu','Delhi') and [Payment Mode]='Online' and Count([Payment Mode])>9;

-- Insight:
--This shows us that non metro States have transacted more in online payments than metro states.

--Q5 Revenue generated by payment modes. 
select [Payment Mode],sum(Profit) as Total_Profit,sum(Revenue) as Total_Revenue from MasterData group by [Payment Mode] order by sum(Revenue) desc;

--Insight:
--Online mode of Payment contributed more in generating revenue than offline mode.






--Q6 Product wise Revenue,Profit and Unit Count
select Q.Pname,P.Product_Id,sum(P.Revenue) as Total_Revenue,sum(P.Profit) as Total_Profit,count(P.Units) as Units_Count from MasterData as P join Product_Name as Q on P.Product_Id=Q.Product_id group by P.Product_Id,Q.Pname order by sum(P.Profit) desc;

--Insight:
--The profit procured  by the products TV,Microwave and Laptop is more than the rest .







--Q7 State wise Revenue,Profit and Unit Count

select P.State,Q.Pname,P.Product_Id,sum(P.Revenue) as Total_Revenue,sum(P.Profit) as Total_Profit,count(P.Units) as Units_Count,round(sum(Profit)/sum(Revenue)*100,2) as Profit_Percentage from MasterData as P join Product_Name as Q on P.Product_Id=Q.Product_id group by P.State,P.Product_Id,Q.Pname order by Total_Revenue desc;

select top(5) P.State,Q.Pname,P.Product_Id,sum(P.Revenue) as Total_Revenue,sum(P.Profit) as Total_Profit,count(P.Units) as Units_Count,round(sum(Profit)/sum(Revenue)*100,2) as Profit_Percentage from MasterData as P join Product_Name as Q on P.Product_Id=Q.Product_id group by P.State,P.Product_Id,Q.Pname order by sum(P.Revenue) asc;

--Insights :
--Jharkhand, Himachal, Karnataka contribute more to the generation of Revenue than other states.
--The company needs to focus on the states namely Haryana, Maharashtra,Arunachal Pradesh,Haryana and Orissa to strategise their business decisions to generate more revenue.

--Q8 State wise count of Payment Mode.

create view Payment_State as
select P.State,P.Count_of_Online_Payment,Q.Count_of_Offline_Payment,(P.Count_of_Online_Payment+Q.Count_of_Offline_Payment) as Total_Count_of_Payments from
(select State ,count([Payment Mode]) as Count_of_Online_Payment from MasterData group by State,[Payment Mode] having [Payment Mode]='Online')P 
join
(select State ,count([Payment Mode]) as Count_of_Offline_Payment from MasterData group by State,[Payment Mode] having [Payment Mode]='Offline')Q on P.State=Q.State;

select * from Payment_State order by Total_Count_of_Payments desc;
--Insight:
--The company can use this analysed data to infer what offers could be given so as to attract the customer base towards online mode of payment.

--Q9. Calculate Profit and Revenue Gender wise.
--Preprocessing:
--This query tells us the types of Gender available in our dataset.
select distinct([Gender_Category]) from MasterData;
select * from MasterData where [Gender_Category] is null;
--We identify that the name Mahesh Kute is a male customer, thereby update the Gender by Male.
update MasterData set Gender_Category='Male' where [Gender_Category] is null;

--Now we are good to go for computing Profit and Revenue Gender wise:
select Gender_Category,sum(Profit) as Total_Profit,sum(Revenue) as Total_Revenue from MasterData group by Gender_Category order by sum(Revenue) desc;
--Insight:
--Male Customers contribute more to the Revenue generated.

--Q 10 Gender wise Product Analysis and Distribution
select P.Gender_Category,count(P.Gender_Category) as Gender_Count,sum(P.Units) as Unit_Count,Q.Pname from MasterData as P join Product_Name as Q on P.Product_Id=Q.Product_id group by P.Gender_Category,Q.Pname order by Unit_Count;
--Insight:
--The company can use this analysed data to infer what offers could be given on the given products so as to target male and female customer base,especially on celebration days.




 create table Product_Name (Pname varchar(20),Product_id varchar(20))
 insert into Product_Name values('Mobile','1000D'),('Laptop','222Y8'),('Washing machine','3000D'),('Microwave','2400C'),('TV','7090E'),('Dishwasher','6667E'),('vaccum cleaner','8821U')
 select * from Product_Name;
 drop table Product_Name
 


